version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: gatsby
    versions:
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-postcss
    versions:
    - 4.2.0
    - 4.3.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: cross-fetch
    versions:
    - 3.1.3
  - dependency-name: gatsby-image
    versions:
    - 3.0.0
    - 3.1.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.5
  - dependency-name: date-fns
    versions:
    - 2.19.0
  - dependency-name: react-helmet-async
    versions:
    - 1.0.9
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.6.1
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.13.0
  - dependency-name: "@types/aws-lambda"
    versions:
    - 8.10.72
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: yup
    versions:
    - 0.32.9
  - dependency-name: flickity
    versions:
    - 2.2.2
