name: gatsby build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: web/public
          key: cache-public-${{ github.sha }}
          restore-keys: |
            cache-public-

      - uses: actions/cache@v2
        with:
          path: web/.cache
          key: cache-cache-${{ github.sha }}
          restore-keys: |
            cache-cache-

      - uses: actions/cache@v2
        with:
          path: web/node_modules
          key: cache-modules-${{ hashFiles('web/yarn.lock') }}
          restore-keys: |
            cache-modules-

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: <registry url>

      - run: yarn --cwd web install

      - name: build
        env:
          GATSBY_SANITY_PROJECT_ID: ${{secrets.GATSBY_SANITY_PROJECT_ID}}
          GATSBY_SANITY_DATASET: ${{secrets.GATSBY_SANITY_DATASET}}
          SANITY_TOKEN: ${{secrets.SANITY_TOKEN}}
        run: yarn --cwd web build

      - name: deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        run: npx netlify-cli deploy --dir=web/public --prod
