[build]
  command = "yarn build"
  functions = "functions"
  ignore = "git diff --quiet HEAD^ HEAD ."
  publish = "public"

[dev]
  command = "yarn dev"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
